var Treelib = require('./index');
var tree4 = Treelib();
tree4.clear();
tree4.path('2/cat');
tree4.setValue('meows');
tree4.show();
console.log(tree4.getValue());
console.log(tree4.getValue('2/cat'));
tree4.path([2,3,4]);
tree4.path([2,7,9]);
tree4.path([4,1,2]);
tree4.path([2,'cat']);
tree4.path([2,'cat','dog']);
console.log(tree4.checkPath('2/cat/dog'));
console.log(tree4.getValue('2/cat'));
tree4.setValue('woof!');
console.log(tree4.tree());
tree4.path([4,1,2]).setValue("Bar");
var val = tree4.getValue([4,1,2]);
console.log(val);
var val2 = tree4.path([4,1,2]).getValue();
console.log(val2);
tree4.show();
var tree = Treelib();
tree.path(['black','15']);
tree.path(['black','15']).setValue('pash');
var list = tree.path(['black','15']).getValue();
console.log(list);
tree.show();
